name: Documentation Deployment

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build documentation
      run: npm run build:docs  # Adjust this to your build script

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3  # Adjust this for other hosting platforms
      with:
        branch: gh-pages  # Adjust this to your deployment branch
        folder: docs  # Adjust this to your documentation directory
        token: ${{ secrets.GITHUB_TOKEN }}
